# Generated by Django 3.1.4 on 2021-01-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=50, unique=True)),
                ('task_status', models.IntegerField(choices=[(0, 'pending'), (1, 'failed'), (2, 'done')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(max_length=8, unique=True)),
                ('summary', models.TextField()),
                ('website_icon_url', models.CharField(max_length=512)),
                ('page_url', models.CharField(max_length=512)),
                ('webpage_title', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('save_summary', models.BooleanField(default=False)),
                ('celery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer_app.summarizertask')),
            ],
        ),
    ]
