# Generated by Django 3.1.4 on 2020-12-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0002_summary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summarization_id',
            new_name='summary_id',
        ),
    ]
