# Generated by Django 3.1.4 on 2020-12-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summarizer_app', '0003_auto_20201230_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='save',
            new_name='save_summary',
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
