# Generated by Django 3.1.4 on 2021-01-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0004_auto_20201230_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='page_url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='summary',
            name='webpage_title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='summary',
            name='website_icon_url',
            field=models.CharField(max_length=512),
        ),
    ]
